Repository puppetlabs/puppetlabs-bootstrap, pull requests merged in 2018-09, with the labels that each got.

#45 (MODULES-7838) Windows task contains typo which causes failure.
  tasks/windows.ps1
Labels: bugfix

#44 pdksync - (MODULES-6805) metadata.json shows support for puppet 6
  metadata.json
Labels: feature

#47 (MODULES-7933) - Release prep for 0.4.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#48 (MODULES-7933) - 0.4.0 Merge Back
  CHANGELOG.md
  metadata.json
Labels: maintenance
