Repository puppetlabs/puppetlabs-bootstrap, pull requests merged in 2019-11, with the labels that each got.

#104 (FM-8275) Add vagrant provision list
  provision.yaml
Labels: maintenance

#112 pdksync - (FM-8634) ensure encrypted communication for fixtures
  .fixtures.yml
Labels: maintenance

#114 pdksync - FM-8499 - remove ubuntu14 support
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#116 (MODULES-10077) - v2.0.0 Release Merge Back
  CHANGELOG.md
  metadata.json
Labels: maintenance

#117 (FM-8686) - Addition of Support for CentOS 8
  metadata.json
  provision.yaml
Labels: feature

#118 (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups
  .gitignore
  .pdkignore
  .project
  .sync.yml
  .travis.yml
  Gemfile
  appveyor.yml
  metadata.json
Labels: maintenance
