Repository puppetlabs/puppetlabs-bootstrap, pull requests merged in 2019-03, with the labels that each got.

#68 pdksync - Remove .project from .gitignore
  .gitignore
  .pdkignore
  .puppet-lint.rc
  .sync.yml
  Rakefile
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#71 (SEN-787) Add implementation metadata
  tasks/init.json
Labels: feature

#72 (SEN-787) Add discovery extension metadata
  tasks/linux.json
  tasks/windows.json
Labels: feature

#67 Ensure certnames are *always* lowercase
  tasks/windows.ps1
Labels: bugfix

#73 (SEN-787) Make linux and windows private
  tasks/init.json
  tasks/linux.json
  tasks/windows.json
Labels: feature
